name: Build, Push & Deploy Node App with Docker

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t myapp .

      # ✅ CD: Deploy to EC2
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/myapp
            git pull origin main
            docker stop myapp || true
            docker rm myapp || true
            docker rmi myapp || true
            docker build -t myapp .
            docker run -d -p 8080:8080 --name myapp myapp
